'use client';

// Talk to the staff: a point-and-click dialogue panel over the office.
// Every word was pre-generated by the morning tick — clicking costs nothing
// (invariant #1). The agent does not know who is asking, and has decided
// not to wonder.

import { useState } from 'react';
import { useOfficeStore } from '@/lib/office/store';
import { agentName } from '@/lib/format';
import type { Dialogues, DialogueTopic } from '@/lib/types';

export function DialoguePanel({ dialogues }: { dialogues: Dialogues }) {
  const open = useOfficeStore((s) => s.openDialogue);
  const [topic, setTopic] = useState<DialogueTopic | null>(null);
  const [answer, setAnswer] = useState<string | null>(null);

  if (!open) return null;
  const dialogue = dialogues[open];
  if (!dialogue) return null;

  const close = () => {
    useOfficeStore.getState().setOpenDialogue(null);
    setTopic(null);
    setAnswer(null);
  };

  return (
    <div className="dialogue-panel">
      <div className="dialogue-head">
        <strong>{agentName(open)}</strong>
        <button
          onClick={close}
          title="Walk away"
        >
          ✕
        </button>
      </div>
      <p className="dialogue-line">{answer ?? topic?.a ?? dialogue.opener}</p>
      <div className="dialogue-options">
        {topic === null
          ? dialogue.topics.map((t) => (
              <button
                key={t.q}
                onClick={() => {
                  setTopic(t);
                  setAnswer(null);
                }}
              >
                {t.q}
              </button>
            ))
          : topic.followups.map((f) => (
              <button
                key={f.q}
                onClick={() => {
                  setAnswer(f.a);
                }}
              >
                {f.q}
              </button>
            ))}
        {topic !== null && (
          <button
            className="dialogue-back"
            onClick={() => {
              setTopic(null);
              setAnswer(null);
            }}
          >
            ← Ask about something else
          </button>
        )}
      </div>
    </div>
  );
}
