'use client';

// Talk to the staff: a point-and-click dialogue balloon anchored ABOVE the
// speaker, like a conversation rather than a form. Every word was
// pre-generated by the morning tick — clicking costs nothing (invariant #1).

import { useState } from 'react';
import { useOfficeStore } from '@/lib/office/store';
import { WORLD } from '@/lib/office/waypoints';
import { agentName } from '@/lib/format';
import type { AgentDialogue, DialogueTopic } from '@/lib/types';

export function DialoguePanel() {
  const open = useOfficeStore((s) => s.openDialogue);
  const dialogues = useOfficeStore((s) => s.dialogues);
  const agents = useOfficeStore((s) => s.agents);
  const [topic, setTopic] = useState<DialogueTopic | null>(null);
  const [answer, setAnswer] = useState<string | null>(null);

  if (!open) return null;
  const dialogue = dialogues[open] as AgentDialogue | undefined;
  const agent = agents[open];
  if (!dialogue || !agent) return null;

  // Anchor above the speaker's head — or below it for the top cubicle row,
  // where "above" would disappear behind the section tabs.
  const leftPct = Math.min(Math.max((agent.x / WORLD.width) * 100, 16), 84);
  const rawTopPct = (agent.y / WORLD.height) * 100;
  const below = rawTopPct < 45;
  const topPct = rawTopPct;

  const close = () => {
    useOfficeStore.getState().setOpenDialogue(null);
    setTopic(null);
    setAnswer(null);
  };

  return (
    <div
      className={`dialogue-panel ${below ? 'below' : ''}`}
      style={{ left: `${leftPct}%`, top: `${topPct}%` }}
    >
      <div className="dialogue-head">
        <strong>{agentName(open)}</strong>
        <button onClick={close} title="Walk away">
          ✕
        </button>
      </div>
      <p className="dialogue-line">{answer ?? topic?.a ?? dialogue.opener}</p>
      <div className="dialogue-options">
        {topic === null
          ? dialogue.topics.map((t) => (
              <button
                key={t.q}
                onClick={() => {
                  setTopic(t);
                  setAnswer(null);
                }}
              >
                {t.q}
              </button>
            ))
          : topic.followups.map((f) => (
              <button
                key={f.q}
                onClick={() => {
                  setAnswer(f.a);
                }}
              >
                {f.q}
              </button>
            ))}
        {topic !== null && (
          <button
            className="dialogue-back"
            onClick={() => {
              setTopic(null);
              setAnswer(null);
            }}
          >
            ← Ask about something else
          </button>
        )}
      </div>
      <div className="dialogue-tail" />
    </div>
  );
}
